# A guide to tensorflow syntax

In [31]:
import tensorflow as tf

In [32]:
a = tf.constant(10)

In [33]:
a

<tf.Tensor 'Const_4:0' shape=() dtype=int32>

In [34]:
b = tf.constant(20)

In [35]:
a + b

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [36]:
a + b

<tf.Tensor 'add_4:0' shape=() dtype=int32>

In [37]:
with tf.Session() as session:
    result = session.run(a+b)

In [38]:
result

30

In [39]:
fill_mat = tf.fill((4,4), 10)

In [40]:
my_zeroes = tf.zeros((4,4))

In [41]:
my_ones = tf.ones((4,4))

In [42]:
my_zeroes, my_ones

(<tf.Tensor 'zeros_1:0' shape=(4, 4) dtype=float32>,
 <tf.Tensor 'ones_1:0' shape=(4, 4) dtype=float32>)

In [29]:
sess = tf.InteractiveSession()

In [44]:
tf_var = (fill_mat, my_zeroes, my_ones)

In [45]:
sess.run(tf_var)

(array([[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]], dtype=int32), array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=float32), array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32))

## Matrix multiplication

In [63]:
a = tf.constant([
    [1,2],
    [3,4]
    ])

In [23]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [24]:
b = tf.constant([[10],[24]])

In [26]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [27]:
tf.matmul(a,b)

<tf.Tensor 'MatMul:0' shape=(2, 1) dtype=int32>

In [29]:
sess = tf.InteractiveSession()

In [30]:
sess.run(tf.matmul(a,b))

array([[ 58],
       [126]], dtype=int32)

## Tensorflow Graphs

In [47]:
n1 = tf.constant(1)
n2 = tf.constant(2)

In [51]:
with tf.Session() as session:
    result = session.run(n1 + n2)

In [52]:
print(result)

3


In [65]:
my_var = tf.Variable(initial_value=a)

In [66]:
init = tf.global_variables_initializer()

In [67]:
sess.run(init)

## Tensorflow Variable and placeholders

### Variables are used to hold actual data
### placeholder, as its name suggests prepare the data type, shape etc. of a variable for future use

In [68]:
my_var

<tf.Variable 'Variable_2:0' shape=(2, 2) dtype=int32_ref>

In [69]:
sess.run(a)

array([[1, 2],
       [3, 4]], dtype=int32)

In [70]:
my_placeholder = tf.placeholder(tf.float32, (2,2))

In [71]:
my_placeholder

<tf.Tensor 'Placeholder:0' shape=(2, 2) dtype=float32>