In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[ 5.2539e-20,  4.5814e-41,  5.2539e-20],
        [ 4.5814e-41,         nan,  0.0000e+00],
        [ 7.6194e+31,  1.5564e+28,  1.8484e+31],
        [ 1.8370e+25,  1.4603e-19,  2.7517e+12],
        [ 7.5338e+28,  3.0313e+32,  6.3828e+28]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[ 0.8568,  0.9670,  0.7208],
        [ 0.1019,  0.3605,  0.1933],
        [ 0.9198,  0.4525,  0.0935],
        [ 0.3885,  0.5205,  0.0549],
        [ 0.7200,  0.7237,  0.1235]])


In [4]:
x.size()

torch.Size([5, 3])

In [7]:
y = torch.rand(5,3)

In [8]:
y

tensor([[ 0.6076,  0.0679,  0.0059],
        [ 0.3993,  0.3630,  0.0535],
        [ 0.2860,  0.0185,  0.5751],
        [ 0.4298,  0.0675,  0.6519],
        [ 0.0343,  0.7267,  0.7651]])

In [35]:
y.add_(x)

tensor([[ 8.3186,  8.7711,  6.4931],
        [ 1.3161,  3.6075,  1.7928],
        [ 8.5640,  4.0908,  1.4169],
        [ 3.9267,  4.7519,  1.1457],
        [ 6.5141,  7.2398,  1.8770]])

In [38]:
y.add(x)

tensor([[ 9.1754,  9.7382,  7.2140],
        [ 1.4180,  3.9680,  1.9861],
        [ 9.4838,  4.5433,  1.5105],
        [ 4.3152,  5.2724,  1.2006],
        [ 7.2341,  7.9635,  2.0005]])

In [39]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([ 0.3291])
0.32909590005874634
